# Generated by Django 2.1.5 on 2019-02-02 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190131_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='License Plate #'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_pass',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Maximum Passengers #'),
        ),
    ]
