# Generated by Django 2.2 on 2019-04-17 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190417_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity'),
        ),
    ]
