# Generated by Django 2.2 on 2019-04-21 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20190418_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Time created')),
                ('fill_quantity', models.PositiveIntegerField(default=1, null=True, verbose_name='Fill Quantity')),
                ('status', models.CharField(choices=[('unfilled', 'unfilled'), ('filled', 'filled')], default='unfilled', max_length=255, verbose_name='Status')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fill_item', to='main.Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill_user', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill_warehouse', to='main.Warehouse')),
            ],
        ),
    ]
