# Generated by Django 2.2 on 2019-04-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='warehouse',
        ),
    ]
