# Generated by Django 2.2 on 2019-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_fill_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='track_id',
        ),
        migrations.AddField(
            model_name='order',
            name='truck_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Truck ID'),
        ),
    ]
