# Generated by Django 2.2 on 2019-04-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190421_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fill',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='fill',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='warehouse',
            new_name='warehouse_id',
        ),
    ]
