# Generated by Django 2.2 on 2019-04-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190421_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_warehouse', to='main.Warehouse'),
        ),
    ]
