# Generated by Django 2.2 on 2019-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190422_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='s_status',
            field=models.CharField(choices=[('not packed', 'not packed'), ('packing', 'packing'), ('not loaded', 'not loaded'), ('loading', 'loading')], default='not packed', max_length=255, verbose_name='Super Status'),
        ),
    ]
