# Generated by Django 2.2 on 2019-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190422_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_prime',
            field=models.BooleanField(default=False, verbose_name='Prime'),
        ),
    ]
