version: '2'

services:
  proxy:
      build: ./proxy
      user: nobody
      command: bash -c "./proxy"
      volumes:
        - ./proxy:/code
        - ./logs:/var/log/erss
      ports:
        - "12345:12345"
