# Generated by Django 2.1.5 on 2019-02-02 08:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_auto_20190201_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='CanShare',
            field=models.BooleanField(default=False, verbose_name='Share Ride Allowed?'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Destination Address'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Required Arrival Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='num_pass',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Passengers #'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('confirmed', 'confirmed'), ('completed', 'completed')], default='null', max_length=255, verbose_name='Status'),
        ),
    ]
