# Generated by Django 2.1.5 on 2019-02-06 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rider', '0005_auto_20190203_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, null=True, related_name='ride_sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(to='rider.Sharer'),
        ),
    ]
