# Generated by Django 2.1.5 on 2019-02-06 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_auto_20190206_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='name',
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, null=True, related_name='ride_sharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sharer',
        ),
    ]
